---
layout: cv
title: Braedan Baird's CV
---
# Braedan Baird
Physicist, Mathematician, Cambridge professor.

<div id="webaddress">
<a href="bbaird77@byui.edu">bbaird77@byui.edu</a>
</div>


## Currently

Studying at BYU-I.

### Specialized in

* Experienced in MS Office Suite
* Familiar with both PC & Mac Formats
* Experienced with the Adobe Creative Suite
* Experienced with RStudio and VS Code Programs
* Certified with the SolidWorks CAD Program
* Experienced with Lathes, Drill Presses & Welding
* Proficient with General Mechanical & Hand Tools


### Interests

Writing, Math, Science, Computer Software, and Computer Hardware.


## Education

`Brigham Young University Idaho`
Attending: 2018, 2021 – Current, Rexburg, ID
`Conestoga Valley Senior High School`	                  
Graduated: 2017, Lancaster, PA


## Occupation

`Crew Member, McDonald’s, Rexburg, ID`				     
Oct 2021 – Dec 2022, Sep 2023 - Current
* Maintained clean, sanitized, and well-organized food preparation zones and prepared cooking supplies, ingredients, and workstations during opening and closing procedures.
* Promoted general customer loyalty and provided customer service.
* Processed payments and counted change to complete transactions.

`Delivery Associate, Amazon, Mount Joy, PA`
January 2023 – Sep 2023
* Lifted and moved packages weighing up to 50 lbs. and efficiently loaded and safely drove delivery vehicle.
* Navigated surrounding areas and delivered packages safely and efficiently.
* Maintained excellent attendance record, consistently arriving at work on time.
* Met and exceeded assigned production standards for quality and quotas.

`Teacher Assistant, Brigham Young University Idaho, Rexburg, ID`
Oct 2021 – May 2022
* Assisted with grading assignments and promptly returning them to students.
* Assisted students with concepts and ideas necessary for their growth and overall success in the course.
* Provided additional help and assistance to individual students to overcome difficulties in comprehension and mastery.




<!-- ### Footer

Last updated: May 2013 -->